"use client";
import React, { useState } from "react";
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";
import { User, Building2, Bell, Shield, Palette, CreditCard, Users, Globe, Save, Settings as SettingsIcon } from "lucide-react";

const sections = [{ id: "profile", label: "Profile", icon: User }, { id: "company", label: "Company", icon: Building2 }, { id: "notifications", label: "Notifications", icon: Bell }, { id: "security", label: "Security", icon: Shield }];

export default function SettingsPage() {
  const [active, setActive] = useState("profile");
  return (
    <DashboardLayout title="Settings" subtitle="Manage your account and preferences">
      <div className="flex gap-6">
        <div className="w-56 shrink-0"><div className="rounded-2xl border border-gray-200/60 bg-white p-2 shadow-sm">{sections.map((s) => <button key={s.id} onClick={() => setActive(s.id)} className={cn("flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-all", active === s.id ? "bg-blue-50 text-blue-700" : "text-gray-600 hover:bg-gray-50")}><s.icon className="h-4 w-4" />{s.label}</button>)}</div></div>
        <div className="flex-1">
          {active === "profile" && <div className="rounded-2xl border border-gray-200/60 bg-white p-6 shadow-sm"><h3 className="text-lg font-semibold text-gray-900 mb-6">Profile Settings</h3><div className="space-y-6"><div className="flex items-center gap-6"><div className="flex h-20 w-20 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-violet-500 text-2xl font-bold text-white">JD</div><Button variant="outline" size="sm">Change Photo</Button></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-medium text-gray-700">First Name</label><input type="text" defaultValue="John" className="flex h-11 w-full rounded-xl border border-gray-200 px-4 py-2 text-sm" /></div><div><label className="mb-2 block text-sm font-medium text-gray-700">Last Name</label><input type="text" defaultValue="Doe" className="flex h-11 w-full rounded-xl border border-gray-200 px-4 py-2 text-sm" /></div><div><label className="mb-2 block text-sm font-medium text-gray-700">Email</label><input type="email" defaultValue="john@omnicrm.com" className="flex h-11 w-full rounded-xl border border-gray-200 px-4 py-2 text-sm" /></div><div><label className="mb-2 block text-sm font-medium text-gray-700">Phone</label><input type="tel" defaultValue="+1 555-0100" className="flex h-11 w-full rounded-xl border border-gray-200 px-4 py-2 text-sm" /></div></div><div className="flex justify-end"><Button><Save className="mr-2 h-4 w-4" /> Save Changes</Button></div></div></div>}
          {active === "notifications" && <div className="rounded-2xl border border-gray-200/60 bg-white p-6 shadow-sm"><h3 className="text-lg font-semibold text-gray-900 mb-6">Notification Preferences</h3><div className="space-y-6">{[{ l: "Email Notifications", d: "Receive notifications via email", e: true }, { l: "Push Notifications", d: "Browser push notifications", e: true }, { l: "Lead Assignments", d: "Get notified when leads are assigned", e: true }, { l: "Deal Updates", d: "Deal stage change alerts", e: true }, { l: "Weekly Reports", d: "Weekly performance summary", e: true }, { l: "AI Insights", d: "AI-generated recommendations", e: true }].map((n) => <div key={n.l} className="flex items-center justify-between"><div><p className="text-sm font-medium text-gray-900">{n.l}</p><p className="text-xs text-gray-500">{n.d}</p></div><Switch defaultChecked={n.e} /></div>)}<div className="flex justify-end"><Button><Save className="mr-2 h-4 w-4" /> Save</Button></div></div></div>}
          {active === "security" && <div className="rounded-2xl border border-gray-200/60 bg-white p-6 shadow-sm"><h3 className="text-lg font-semibold text-gray-900 mb-6">Security Settings</h3><div className="space-y-4"><div className="rounded-xl border border-gray-200 p-4"><div className="flex items-center justify-between"><div><p className="font-medium text-gray-900">Two-Factor Authentication</p><p className="text-sm text-gray-500">Extra security layer</p></div><Switch defaultChecked /></div></div><div className="rounded-xl border border-gray-200 p-4"><div className="flex items-center justify-between"><div><p className="font-medium text-gray-900">SSO Login</p><p className="text-sm text-gray-500">Single Sign-On</p></div><Button variant="outline" size="sm">Configure</Button></div></div><div className="rounded-xl border border-gray-200 p-4"><p className="font-medium text-gray-900 mb-3">Change Password</p><div className="space-y-3"><input type="password" placeholder="Current password" className="flex h-11 w-full rounded-xl border border-gray-200 px-4 py-2 text-sm" /><input type="password" placeholder="New password" className="flex h-11 w-full rounded-xl border border-gray-200 px-4 py-2 text-sm" /><Button size="sm">Update Password</Button></div></div></div></div>}
          {!["profile", "notifications", "security"].includes(active) && <div className="rounded-2xl border border-gray-200/60 bg-white p-12 text-center shadow-sm"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-gray-10"><SettingsIcon className="h-8 w-8 text-gray-400" /></div><h3 className="text-lg font-semibold text-gray-900">{sections.find((s) => s.id === active)?.label} Settings</h3><p className="mt-2 text-sm text-gray-500">Available in the full version.</p></div>}
        </div>
      </div>
    </DashboardLayout>
  );
}
