"use client";
import React from "react";
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { Shield, Users, Settings, Zap, Server, Building2, Palette } from "lucide-react";

export default function AdminPage() {
  return (
    <DashboardLayout title="Admin Panel" subtitle="System administration">
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-4">
        {[{ l: "System Status", v: "Healthy", icon: Server, g: "from-emerald-500 to-emerald-600" }, { l: "Uptime", v: "99.98%", icon: Shield, g: "from-blue-500 to-blue-600" }, { l: "Active Users", v: "847", icon: Users, g: "from-purple-500 to-purple-600" }, { l: "Storage", v: "67%", icon: Settings, g: "from-amber-500 to-amber-600" }].map((s) => (
          <div key={s.l} className="rounded-2xl border border-gray-200/60 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-gray-500">{s.l}</p><p className="mt-1 text-2xl font-bold text-gray-900">{s.v}</p></div><div className={cn("flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br", s.g)}><s.icon className="h-5 w-5 text-white" /></div></div></div>
        ))}
      </div>
      <div className="grid gap-6 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-200/60 bg-white p-6 shadow-sm"><div className="flex items-center justify-between mb-4"><h3 className="text-lg font-semibold text-gray-900">Tenant Management</h3><Button size="sm"><Building2 className="mr-2 h-4 w-4" /> Add Tenant</Button></div><div className="space-y-3">{[{ n: "Acme Corp", p: "Enterprise", u: 45, s: "Active" }, { n: "Global Manufacturing", p: "Business", u: 28, s: "Active" }, { n: "FastTrack Logistics", p: "Enterprise", u: 62, s: "Active" }, { n: "Urban Properties", p: "Starter", u: 8, s: "Trial" }].map((t) => <div key={t.n} className="flex items-center justify-between rounded-xl border border-gray-100 p-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-blue-500 to-violet-500 text-xs font-bold text-white">{t.n[0]}</div><div><p className="text-sm font-medium text-gray-900">{t.n}</p><p className="text-xs text-gray-500">{t.u} users - {t.p}</p></div></div><Badge variant={t.s === "Active" ? "success" : "info"}>{t.s}</Badge></div>)}</div></div>
        <div className="rounded-2xl border border-gray-200/60 bg-white p-6 shadow-sm"><h3 className="text-lg font-semibold text-gray-900 mb-4">User Roles</h3><div className="space-y-3">{[{ r: "Super Admin", u: 2, p: "Full access" }, { r: "Company Owner", u: 5, p: "All modules" }, { r: "Manager", u: 24, p: "Team management" }, { r: "Employee", u: 456, p: "Assigned modules" }, { r: "Customer Portal", u: 233, p: "Portal only" }].map((r) => <div key={r.r} className="flex items-center justify-between rounded-xl border border-gray-100 p-3"><div><p className="text-sm font-medium text-gray-900">{r.r}</p><p className="text-xs text-gray-500">{r.p}</p></div><span className="text-sm font-medium text-gray-600">{r.u} users</span></div>)}</div></div>
        <div className="rounded-2xl border border-gray-200/60 bg-white p-6 shadow-sm"><div className="flex items-center gap-2 mb-4"><Palette className="h-5 w-5 text-gray-600" /><h3 className="text-lg font-semibold text-gray-900">White Label</h3></div><div className="space-y-4"><div><label className="mb-2 block text-sm font-medium text-gray-700">Brand Name</label><input type="text" defaultValue="OmniCRM" className="flex h-11 w-full rounded-xl border border-gray-200 px-4 py-2 text-sm" /></div><div><label className="mb-2 block text-sm font-medium text-gray-700">Custom Domain</label><input type="text" defaultValue="crm.yourcompany.com" className="flex h-11 w-full rounded-xl border border-gray-200 px-4 py-2 text-sm" /></div><div><label className="mb-2 block text-sm font-medium text-gray-700">Primary Color</label><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-lg bg-blue-600" /><input type="text" defaultValue="#2563EB" className="flex h-11 w-32 rounded-xl border border-gray-200 px-4 py-2 text-sm font-mono" /></div></div><Button><Settings className="mr-2 h-4 w-4" /> Save Branding</Button></div></div>
        <div className="rounded-2xl border border-gray-200/60 bg-white p-6 shadow-sm"><h3 className="text-lg font-semibold text-gray-900 mb-4">System Health</h3><div className="space-y-3">{[{ l: "Database", s: "PostgreSQL 15.4", h: true }, { l: "Cache", s: "Redis 7.2", h: true }, { l: "Storage", s: "S3 - 2.4TB", h: true }, { l: "AI Service", s: "OpenAI Connected", h: true }, { l: "Email", s: "SendGrid Active", h: true }, { l: "SMS", s: "Twilio Active", h: true }].map((i) => <div key={i.l} className="flex items-center justify-between rounded-xl border border-gray-100 p-3"><div><p className="text-sm font-medium text-gray-900">{i.l}</p><p className="text-xs text-gray-500">{i.s}</p></div><div className={cn("h-2.5 w-2.5 rounded-full", i.h ? "bg-emerald-500" : "bg-amber-500")} /></div>)}</div></div>
      </div>
    </DashboardLayout>
  );
}
